#%RAML 0.8
---
title: Example API
version: 1
baseUri: http://example.com
/basic-auth/<user>/<passwd>:
  displayName: Basic Auth
  description: Prompts the user for authorization using HTTP Basic Auth
  delete:
    responses:
      401:
      200:
        body:
          application/json: